---
# tasks file for ansible-role-waypoint

- name: Include OS specific variables.
  include_vars: "{{ ansible_system }}.yml"

- name: Install Hashicorp waypoint
  include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_system }}.yml"
        - setup-Linux.yml
      paths:
        - 'tasks'
