---
# tasks file for install waypoint on Windows system

- name: Windows | Find all versions of waypoint
  ansible.windows.win_uri:
    url: https://releases.hashicorp.com/waypoint/index.json
    return_content: true
  register: _waypoint_index
  when: waypoint_version == 'latest'
  check_mode: false

- name: Windows | Finds the latest waypoint version when latest var is define
  ansible.builtin.set_fact:
    _waypoint_version: "{{ (_waypoint_index.content | from_json).versions | reject('search', '-') | list | sort_versions | last }}"
  when: waypoint_version == 'latest'

- name: Windows | Use the specified waypoint version when latest var is not define
  ansible.builtin.set_fact:
    _waypoint_version: "{{ waypoint_version }}"
  when: waypoint_version != 'latest'

# This task avoids downloading waypoint every time
- name: Windows | Check if waypoint is present on Windows with the right version
  ansible.windows.win_command: waypoint -version
  register: _waypoint_installed_version
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Windows | Download waypoint
  ansible.windows.win_get_url:
    url: "{{ waypoint_pkg_url }}"
    dest: '%TEMP%\waypoint_{{ _waypoint_version }}_windows_amd64.zip'
    checksum_url: "{{ waypoint_checksum_url if waypoint_checksum_verify else omit }}"
    checksum_algorithm: "{{ 'sha256' if waypoint_checksum_verify else omit }}"
  check_mode: false
  when: _waypoint_version not in ( _waypoint_installed_version.stdout_lines | default(['empty']) | first )

- name: Windows | Create waypoint folder
  ansible.windows.win_file:
    path: "{{ waypoint_path }}"
    state: directory

- name: Windows | Install waypoint
  community.windows.win_unzip:
    src: '%TEMP%\waypoint_{{ _waypoint_version }}_windows_amd64.zip'
    dest: "{{ waypoint_path }}"
  when: _waypoint_version not in ( _waypoint_installed_version.stdout_lines | default(['empty']) | first )

- name: Windows | Add waypoint to PATH
  ansible.windows.win_path:
    elements: "{{ waypoint_path }}"
