---
# tasks file for install waypoint on Linux and Unix system

- name: Linux | Find all versions of Hashicorp waypoint
  uri:
    url: https://releases.hashicorp.com/waypoint/index.json
    return_content: yes
  register: waypoint_index
  when: waypoint_version == "latest"
  check_mode: no

- name: Linux | Finds the latest waypoint version when latest var is define
  set_fact:
    waypoint_version_to_install: "{{ (waypoint_index.content | from_json).versions | reject('search','-') | list | sort_versions | last }}"
  when: waypoint_version == 'latest'

- name: Linux | Use the specified waypoint version when latest var is not define
  set_fact:
    waypoint_version_to_install: "{{ waypoint_version }}"
  when: waypoint_version != 'latest'

# This task avoids downloading waypoint every time
- name: Linux/Unix | Check if waypoint is present with the right version
  command: "{{ waypoint_path }}/waypoint -version"
  register: waypoint_installed_version
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Linux | Install waypoint
  unarchive:
    src: "{{ waypoint_pkg_url }}"
    dest: "{{ waypoint_path }}"
    remote_src: yes
  when: waypoint_version_to_install not in ( waypoint_installed_version.stdout_lines | default(['empty'], true) | first )
