---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | waypoint should be functionnal
      ansible.builtin.command: waypoint --version
      register: waypoint_result

    - name: Linux | Verify commands outputs
      ansible.builtin.assert:
        that:
          - waypoint_result.rc == 0
        success_msg: "All tests passed"
      when: lookup('env', 'waypoint_version') == "latest"

    - name: Linux | Verify commands outputs
      ansible.builtin.assert:
        that:
          - waypoint_result.rc == 0
          - lookup('env', 'waypoint_version') in waypoint_result.stdout
        success_msg: "All tests passed"
      when: lookup('env', 'waypoint_version') != "latest"
